FuzzyDatabaseConfig:
  BackboneConfiguration:
    reference_groups:
      ID:
        - "Customer_ID(1)" # Must be only one
      Name:
        - "Customer_ID(2)"
        - "Customer_Name(6)"
        - "Industrial_Sector(2)"
      Address:
        - "Customer_Name(1)"
        - "Address(6)"
    target_groups:
      ID:
        - "Customer_ID(5)"
        - "Customer_Name(1)"
      Name:
        - "Customer_Name(4)"
        - "Customer_ID(1)"
        - "Industrial_Sector(1)"
      Address:
        - "Customer_Name(1)"
        - "Address(6)"
        - "Industrial_Sector(1)"
    ref_to_tgt:
      ID: "ID"
      Name: "Name"
      Address: "Address"
    tgt_to_ref:
      ID: "ID"
      Name: "Name"
      Address:
        - "Address"
        - "Name"
    reference_key_col: "Customer_ID"
    target_key_col: "Customer_ID"
  DataToConsume:
    ReferenceTable: "./Sample_Dataset/Primary_Reference_Table.xlsx"
    MessyTable: "./Sample_Dataset/Secondary_Data.xlsx"
  OperatingDir: "./OperatingDir"
  RegexPreprocessing:
    Customer_ID: "((?<![/\\d])\\d+(?![/\\d]))"
